### ISSUE TITLE
Is the T50K equivalent to the T50?

### ISSUE THREAD

**Issue by bjmc** [AgostinoA/OpenWrt-ZyXEL-VMG8825-T50#1]
Or are they different hardware? I asked Zyxel for the firmware for my device and they gave me this: https://github.com/bjmc/VMG8825-T50K

**Comment by AgostinoA** [comment]
I think they are the same, honestly on the official website, I can't find the version without K. If you managed to get into the router. Read from the kernel, the chipset architecture

**Comment by AgostinoA** [comment]
If you need help getting in let me know.

**Comment by AgostinoA** [comment]
Anyway, thank you for the firmware, I have been stopped for days for work and university.
On the weekend, I want to dedicate myself a little.

The base of firmware, they use is based on Openwrt

**Comment by frosit** [comment]
I believe they are the same, the spreadsheet also indicates that the same project for a different customer gets a new model ID. I have the TMobile version here, router says it's T50, the spreadsheet states the TMobile model id is T50K. I can't even find a regular T50 anywhere. https://github.com/AgostinoA/OpenWrt-ZyXEL-VMG8825-T50/blob/main/stock/V5.50(ABOM.3)C0/docs_zyxel/Zyxel_Model_ID_and_Firmware_version.xlsx

**Comment by AgostinoA** [comment]
Thank you for the confirmation @frosit  :)

**Comment by 7e4** [comment]
i have an "original" VMG8825-T50, with Firmware version: V5.50(ABOM.1)D0, Have requested the source at Zyxel. Let's see what they'll give me.

**Comment by AgostinoA** [comment]
@7e4 I have perfect you can load the firmware in the stock folder with a pull request, I would be very happy

**Comment by splashsc** [comment]
> 我有一个“原始”VMG8825-T50，固件版本：V5.50(ABOM.1)D0，已在 Zyxel 请求源。让我们看看他们会给  Please a VMG8825-T50 raw firmware，thank u！

**Comment by AgostinoA** [comment]
@scgs66 thanks that you are interested in the router, on the network I found only these raw firmware, I do not have anything else. If you can do some more extensive research and find it, I ask you to upload everything related to this router. There is a lot of chance of success, I started working after July to complete my university career. Thanks for everything and everyone.

For other situations, we open other issues, thanks
